import {createSlice} from '@reduxjs/toolkit';
import {categoryData} from '../actions';
import images from  '@utils/images';

const initialState = {
  loading: false,
  categories: [
    {
      type: "podiItems",
      data: [
        {
          id: '#podi01',
          name: "Dhal Powder",
          type: 'podiItems',
          original_url: images.powder1,
          quantity: "500",
          weight: "500",
          price: 120,
          sale_price: 230,
        },
        {
          id: '#podi02',
          name: "Idly Powder",
          type: 'podiItems',
          original_url: images.powder2,
          quantity: "250",
          weight: "250",
          price: 50,
          sale_price: 230,
        },
        {
          id: '#podi03',
          name: "Karuvapillai Powder",
          type: 'podiItems',
          original_url: images.powder3,
          quantity: "300",
          weight: "300",
          price: 100,
          sale_price: 230,
        },
        {
          id: '#podi04',
          name: "Angaya Powder",
          type: 'podiItems',
          original_url: images.powder4,
          quantity: "400",
          weight: "400",
          price: 80,
          sale_price: 230,
        },
        {
          id: '#podi05',
          name: "Ellu Idly Powder",
          type: 'podiItems',
          original_url: images.powder5,
          quantity: "200",
          weight: "200",
          price: 60,
          sale_price: 230,
        },
        {
          id: '#podi06',
          name: "Coriander Powder",
          type: 'podiItems',
          original_url: images.powder6,
          quantity: "500",
          weight: "500",
          price: 150,
          sale_price: 230,
        },
        {
          id: '#podi07',
          name: "Rasam Powder",
          type: 'podiItems',
          original_url: images.powder7,
          quantity: "300",
          weight: "300",
          price: 90,
          sale_price: 230,
        },
        {
          id: '#podi08',
          name: "Garlic Dhal Powder",
          type: 'podiItems',
          original_url: images.powder8,
          quantity: "250",
          weight: "250",
          price: 70,
          sale_price: 230,
        },
        {
          id: '#podi09',
          name: "Garlic Idly Powder",
          type: 'podiItems',
          original_url: images.powder9,
          quantity: "500",
          weight: "500",
          price: 130,
          sale_price: 230,
        },
        {
          id: '#podi10',
          name: "Puliyodharai Powder",
          type: 'podiItems',
          original_url: images.powder10,
          quantity: "200",
          weight: "200",
          price: 40,
          sale_price: 230,
        },
        {
          id: '#podi11',
          name: "Ellu",
          type: 'podiItems',
          original_url: images.powder11,
          quantity: "300",
          weight: "300",
          price: 120,
          sale_price: 230,
        },
        {
          id: '#podi12',
          name: "Coconut Powder",
          type: 'podiItems',
          original_url: images.powder12,
          quantity: "250",
          weight: "250",
          price: 75,
          sale_price: 230,
        },
        {
          id: '#podi13',
          name: "Sambar Powder",
          type: 'podiItems',
          original_url: images.powder13,
          quantity: "100",
          weight: "100",
          price: 50,
          sale_price: 230,
        },
      ]
    },
    {
      type: "vathal",
      data: [
        {
          id: '#vathal1',
          name: "Manathakali Vathal",
          type: "vathal",
          original_url: images.vathal1,
          quantity: "500",
          weight: "500",
          price: 150,
          sale_price: 230,
        },
        {
          id: '#vathal2',
          name: "Sundaikai Vathal",
          type: "vathal",
          original_url: images.vathal2,
          quantity: "500",
          weight: "500",
          price: 140,
          sale_price: 230,
        },
        {
          id: '#vathal3',
          name: "More Mellkai",
          type: "vathal",
          original_url: images.vathal3,
          quantity: "500",
          weight: "500",
          price: 160,
          sale_price: 230,
        },
        {
          id: '#vathal4',
          name: "Kathirikai Vathal",
          type: "vathal",
          original_url: images.vathal4,
          quantity: "500",
          weight: "500",
          price: 130,
          sale_price: 230,
        },
        {
          id: '#vathal5',
          name: "Sukkangai Vathal",
          type: "vathal",
          original_url: images.vathal5,
          quantity: "500",
          weight: "500",
          price: 170,
          sale_price: 230,
        },
        {
          id: '#vathal6',
          name: "Kothavarangai Vathal",
          type: "vathal",
          original_url: images.vathal6,
          quantity: "500",
          weight: "500",
          price: 180,
          sale_price: 230,
        },
        {
          id: '#vathal7',
          name: "Manathakali Vathal No Salt",
          type: "vathal",
          original_url: images.vathal7,
          quantity: "500",
          weight: "500",
          price: 150,
          sale_price: 230,
        },
        {
          id: '#vathal8',
          name: "Sundaikai Vathal No Salt",
          type: "vathal",
          original_url: images.vathal8,
          quantity: "500",
          weight: "500",
          price: 140,
          sale_price: 230,
        },
        {
          id: '#vathal9',
          name: "Vendakai Vathal",
          type: "vathal",
          original_url: images.vathal9,
          quantity: "500",
          weight: "500",
          price: 150,
          sale_price: 230,
        },
        {
          id: '#vathal10',
          name: "Pavakkai Vathal",
          type: "vathal",
          original_url: images.vathal10,
          quantity: "500",
          weight: "500",
          price: 160,
          sale_price: 230,
        },
        {
          id: '#vathal11',
          name: "Thamarai Thandu Vathal",
          type: "vathal",
          original_url: images.vathal11,
          quantity: "500",
          weight: "500",
          price: 190,
          sale_price: 230,
        },
      ]
    },
    {
      type: "vadam",
      data:[
        {
          id: '#vadam1',
          name: "Omapodi Vadam",
          type: "vadam",
          original_url: images.vadam1,
          quantity: "500",
          weight: "500",
          price: 150,
          sale_price: 230,
        },
        {
          id: '#vadam2',
          name: "Elai Vadam Big",
          type: "vadam",
          original_url: images.vadam2,
          quantity: "500",
          weight: "500",
          price: 160,
          sale_price: 230,
        },
        {
          id: '#vadam3',
          name: "Tomato Vadam",
          type: "vadam",
          original_url: images.vadam3,
          quantity: "500",
          weight: "500",
          price: 140,
          sale_price: 230,
        },
        {
          id: '#vadam4',
          name: "Pudina Vadam",
          type: "vadam",
          original_url: images.vadam4,
          quantity: "500",
          weight: "500",
          price: 170,
          sale_price: 230,
        },
        {
          id: '#vadam5',
          name: "Seeraga Vadam",
          type: "vadam",
          original_url: images.vadam5,
          quantity: "500",
          weight: "500",
          price: 150,
          sale_price: 230,
        },
        {
          id: '#vadam6',
          name: "Potato Vadam",
          type: "vadam",
          original_url: images.vadam6,
          quantity: "500",
          weight: "500",
          price: 160,
          sale_price: 230,
        },
        {
          id: '#vadam7',
          name: "Wheel Vadam",
          type: "vadam",
          original_url: images.vadam7,
          quantity: "500",
          weight: "500",
          price: 130,
          sale_price: 230,
        },
        {
          id: '#vadam8',
          name: "Onion Vadam",
          type: "vadam",
          original_url: images.vadam8,
          quantity: "500",
          weight: "500",
          price: 140,
          sale_price: 230,
        },
        {
          id: '#vadam9',
          name: "Jeversi Vadam",
          type: "vadam",
          original_url: images.vadam9,
          quantity: "500",
          weight: "500",
          price: 150,
          sale_price: 230,
        },
        {
          id: '#vadam10',
          name: "Elai Vadam Small",
          type: "vadam",
          original_url: images.vadam10,
          quantity: "500",
          weight: "500",
          price: 160,
          sale_price: 230,
        },
        {
          id: '#vadam11',
          name: "Carrot Vadam",
          type: "vadam",
          original_url: images.vadam11,
          quantity: "500",
          weight: "500",
          price: 170,
          sale_price: 230,
        },
        {
          id: '#vadam12',
          name: "Chili Vadam",
          type: "vadam",
          original_url: images.vadam12,
          quantity: "500",
          weight: "500",
          price: 150,
          sale_price: 230,
        },
        {
          id: '#vadam13',
          name: "Beetroot Vadam",
          type: "vadam",
          original_url: images.vadam13,
          quantity: "500",
          weight: "500",
          price: 140,
          sale_price: 230,
        },
        {
          id: '#vadam14',
          name: "Somas Vadam",
          type: "vadam",
          original_url: images.vadam14,
          quantity: "500",
          weight: "500",
          price: 150,
          sale_price: 230,
        },
        {
          id: '#vadam15',
          name: "Finger Vadam",
          type: "vadam",
          original_url: images.vadam15,
          quantity: "500",
          weight: "500",
          price: 160,
          sale_price: 230,
        },
        {
          id: '#vadam16',
          name: "Green Chili Vadam",
          type: "vadam",
          original_url: images.vadam16,
          quantity: "500",
          weight: "500",
          price: 150,
          sale_price: 230,
        },
        {
          id: '#vadam17',
          name: "Neetu Vadam",
          type: "vadam",
          original_url: images.vadam17,
          quantity: "500",
          weight: "500",
          price: 140,
          sale_price: 230,
        },
        {
          id: '#vadam18',
          name: "Ribbon Vadam",
          type: "vadam",
          original_url: images.vadam18,
          quantity: "500",
          weight: "500",
          price: 170,
          sale_price: 230,
        },
        {
          id: '#vadam19',
          name: "Kuzhambu Vadam",
          type: "vadam",
          original_url: images.vadam19,
          quantity: "500",
          weight: "500",
          price: 160,
          sale_price: 230,
        },
        {
          id: '#vadam20',
          name: "Semiya Vadam",
          type: "vadam",
          original_url: images.vadam20,
          quantity: "500",
          weight: "500",
          price: 150,
          sale_price: 230,
        },
      ]
    }
  ],
};

const categorySlice = createSlice({
  name: 'category',
  initialState,
  reducers: {},
  extraReducers: builder => {
    //Category Cases
    builder.addCase(categoryData.pending, (state, action) => {
      state.loading = true;
    });
    builder.addCase(categoryData.fulfilled, (state, action) => {
      state.categories = action?.payload?.data;
      state.loading = false;
    });
    builder.addCase(categoryData.rejected, (state, action) => {
      state.loading = false;
    });
  },
});
export default categorySlice.reducer;
